language: "node_js"
node_js:
    - "node"
before_install:
  - npm install

#install:
#  - NODE_ENV=dev npm install

#before_script:
 - npm run lint

script:
- npm run test
- npm run report-coverage

# install:
#  - npm install -g codecov
# script:
#  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
#  - codecov
#  - npm run test

# c448f245-27a0-4f18-b3b3-60ddc98b2350
#before_deploy:
#  - npm run build:prod
