language: "node_js"
node_js:
    - "node"
before_install:
  - npm install

#install:
#  - NODE_ENV=dev npm install

#before_script:
#  - npm run lint

install:
 - npm install -g codecov
script:
 - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
 - codecov
 - npm run test
 
# c448f245-27a0-4f18-b3b3-60ddc98b2350
#before_deploy:
#  - npm run build:prod

#deploy:
#  provider: npm
#  email: shz145@ucsd.com
#  api_key: $NPM_TOKEN
#  skip_cleanup: true
#  on:
#    tags: true